#!/usr/bin/env python3
"""Rebuild the vendored engine (worldexplorer/_engine.py) by amalgamating
engine_src/*.py -- the same modular source the harness is developed in. The
single-file engine is what gets imported at runtime (and shipped in the wheel).
Run after editing anything under engine_src/:  python sync_engine.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
parts = sorted((ROOT / "engine_src").glob("*.py"))
if not parts:
    raise SystemExit("engine_src/ is empty -- nothing to build.")
body = "".join(p.read_text() for p in parts)
hdr = ("# AUTO-GENERATED by sync_engine.py from engine_src/ -- DO NOT EDIT THIS FILE.\n"
       "# Edit the modules in engine_src/ and re-run: python sync_engine.py\n")
out = ROOT / "worldexplorer" / "_engine.py"
out.write_text(hdr + body)
print(f"rebuilt {out.name} from {len(parts)} modules ({out.stat().st_size} bytes)")
for p in parts:
    print(f"  {p.name:34s} {len(p.read_text().splitlines()):5d} lines")
